  server:
    port: 8086

  spring:
    kafka:
      bootstrap-servers: localhost:9092

      producer:
        value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

      consumer:
        group-id: pedido-group
        auto-offset-reset: earliest
        enable-auto-commit: false
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

      listener:
        ack-mode: manual
        concurrency: 2

      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true